### PR TITLE
Persist with callbacks

### PR DESCRIPTION
**Pull request by omrishuva**

### CODE REVIEW

**Comment by unorthodoxgeek** [comment]
I don't understand why this is needed. please write a short explanation, so I can consider this PR.
from how it seems, when the persist with callbacks flag is raised the gem is effectively disabled...
thanks dude :smile:

**Comment by omrishuva** [comment]
In the new design we retrive all the data from elastic search and try not do any sql query, so every time we update the db we need to update elastic search as well and the indexing is happening in an after save callback.

**Comment by unorthodoxgeek** [comment]
ok, I now see the error of my ways :smile:

**Comment by omrishuva** [comment]
thanks for merging dude.

**Comment by unorthodoxgeek** [comment]
next time, please bump the version in the PR so I don't have to.
anyway, pushed version 0.1.2 to rubygems. update it in your gemfile (bundle update visit_counter)

**Comment by unorthodoxgeek** [comment]
oh, and I forgot. please add the new feature to the README file and open a new PR for it. thanks.

**Comment by omrishuva** [comment]
ok , no problem

**Pull request merged**
